### ISSUE TITLE
Font Size, too small - Mobile

### ISSUE THREAD

**Issue by imarchit19** [imarchit19/Roll-The-Dice#5]
While in mobile mode, the font size is very small.

**Comment by Capt-Titanium** [comment]
I can fix that for you :) 
please assign

**Comment by priteshsingh-vats** [comment]
I can fix it!
you can assign it to me

**Comment by Capt-Titanium** [comment]
done and sent PR #6  please check

**Comment by Capt-Titanium** [comment]
@imarchit19 the PR I sent where I increased the font size as requested by you is your issue is not being counted in hacktober fest. I request you to label it "hacktoberfest-accepted" to make it count.

**Comment by imarchit19** [comment]
@Capt-Titanium I had already assigned it to someone, do note that.
Marking it for now.
